[project]
name = "paraxcel"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "python-docx",
    "pydantic",
    "openpyxl",
]

# Explicitly defining classifiers
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.setuptools.packages.find]
# Defining package location and exclusions
where = ["src"]
exclude = ["tests*"]

# Include assets (like icon.png)
[tool.setuptools.package-data]
"paraxcel" = ["assets/*.png"]

[project.scripts]
paraxcel = "src.app:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
